{% set name = "ezconda" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ezconda-{{ version }}.tar.gz
  sha256: 523a260e17acdb9c0a0444a80f577bf856f8be857bfa4dc5b8fdc28fdcc1b222

build:
  number: 0
  noarch: python
  entry_points:
    - ezconda = ezconda.main:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - python >=3.6
    - pyyaml >=5.4.1,<6.0.0
    - rich >=10.11.0,<11.0.0
    - typer >=0.4.0
    - tomlkit >=0.9.0
    - conda >=4.8
    - mamba

test:
  imports:
    - ezconda
    - ezconda.experimental
  commands:
    - pip check
    - ezconda --help
  requires:
    - pip

about:
  home: https://github.com/SarthakJariwala/ezconda
  summary: Create, Manage, Re-create conda environments & specifications with ease.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SarthakJariwala
